version: "3.8"

# This scripts will start up all containers that are needed for development.
# After having run docker compose up
# You can start up the Niord app by standing in the niord-dk-web and run > mvn quarkus:dev 

services:
# https://activemq.apache.org/components/artemis/documentation/latest/docker.html

  niord-mq:
    image: apache/activemq-artemis:2.31.2 
    container_name: "niord-mq"
    ports:
      - "5672:5672"
      - "8161:8161"
    restart: no
#    volumes:
#      - ./niord_home/artemis:/var/lib/artemis-instance
    environment:
      ARTEMIS_USER: ${NIORD_MQ_USER:-niord}
      ARTEMIS_PASSWORD: ${NIORD_MQ_PASSWORD:-niord}
   
  niord-db:
    image: mysql:${MYSQL_VERSION:-8.0.35}
    container_name: niord-db
    ports:
      - "3306:3306"
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql}
      MYSQL_USER: niord
      MYSQL_PASSWORD: ${NIORD_DB_PASSWORD:-niord}
      MYSQL_DATABASE: niord
#    volumes:
#      - ./niord_home/niord-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pniord"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE  # Disables som mbind warnings

  niord-keycloak-db:
    image: postgres:latest
    container_name: niord-keycloak-db
    restart: no
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
#    volumes:
#      - ./niord_home/niord-keycloak-db:/var/lib/postgresql/data
 
  niord-keycloak:
    image: quay.io/keycloak/keycloak:${NIORD_KEYCLOAK_VERSION:-22.0.5}
    container_name: niord-keycloak
    restart: no
    command: ['start-dev', '--import-realm', '--http-relative-path /auth', '--hostname-url=http://localhost:8080/auth/']
    volumes:
      - ./niord-bootstrap-realm-dk.json:/opt/keycloak/data/import/niord-bootstrap-realm.json
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL_HOST: niord-keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KCDB_PASSWORD:-keycloak}
    healthcheck:
      test: ["CMD-SHELL", "cat < /dev/null > /dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 50s
      retries: 10
    depends_on:
      - niord-keycloak-db
    ports:
      - "8080:8080"
      
  niord-smtp:
    image: mailhog/mailhog
    container_name: niord-smtp
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui      
      
  niord-jaeger:
    image: jaegertracing/all-in-one:1.6
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"      